awslabs/service-workbench-on-aws

- addons/addon-base-raas/packages/base-raas-post-deployment/lib/steps/create-service-catalog-portfolio.js
N/A
Placing product artifact description in the correct place.
Checklist: 
> Add desc in product artifact params

- addons/addon-base-raas-ui/packages/base-raas-ui/src/helpers/api.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/aws-accounts/AwsAccount.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/aws-accounts/AwsAccountsStore.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/aws-accounts/Budget.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/aws-accounts/BudgetStore.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/aws-accounts/__tests__/BudgetStore.test.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/forms/AddBudgetForm.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/accounts/AwsAccountsList.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/accounts/UpdateBudget.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/plugins/routes-plugin.js
- addons/addon-base-raas/package-lock.json
- addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/onboard-account.cfn.yml
- addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/budgets-controller.js
- addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/routes-plugin.js
- addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/services-plugin.js
- addons/addon-base-raas/packages/base-raas-services/lib/budgets/__tests__/budgets-service.test.js
- addons/addon-base-raas/packages/base-raas-services/lib/budgets/budget-base-templates.js
- addons/addon-base-raas/packages/base-raas-services/lib/budgets/budgets-service.js
- addons/addon-base-raas/packages/base-raas-services/lib/schema/create-budget.json
- addons/addon-base-raas/packages/base-raas-services/package.json
- docs/docs/user_guide/sidebar/admin/accounts/aws_accounts/set_account_budget.md
- docs/sidebars.js
- pnpm-lock.yaml
Create and update budget with associated thresholds and notifications
Unit test for budget service 
Unit test for budget store 
Tested in local deployment 
Documentation
Checklist: 
> Add budget integration

- CHANGELOG.md
> Add initial CHANGELOG file

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> docs: update Changelog

- addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
Unexpected exceptions were being ignored
Unknown/unexpected exceptions should be thrown.
Checklist: 
> Bugfix: Exceptions going unseen

- docs/docs/user_guide/sidebar/common/workspaces/accessing_a_workspace.md
- main/solution/machine-images/README.md
N/A
Added documentation for RStudio auto-stop
Checklist: 
> fix: added documentation for auto-stop

- docs/docs/user_guide/sidebar/common/workspaces/accessing_a_workspace.md
- main/solution/machine-images/README.md
- main/solution/machine-images/config/infra/files/rstudio/check-idle
- main/solution/machine-images/config/infra/provisioners/provision-rstudio.sh
https://github.com/awslabs/service-workbench-on-aws/issues/185
Changing check-idle logic for RStudio.
Checklist: 
> fix: changing rstudio check-idle logic

- CHANGELOG.md
> docs: Update change log for 1.3.1 release

- main/solution/backend/config/infra/cloudformation.yml
More than 50 tables were being created simultaneously by a CfN stack. 
Added dependencies between tables to reduce simultaneous creations.
Checklist: 
> fix: adding dependencies for table creation

- CHANGELOG.md
> docs: Update change log for 1.3.2 release

- main/cicd/cicd-source/config/settings/example-codecommit.yml
- main/config/settings/example.yml
- main/solution/machine-images/config/settings/example.yml
- pnpm-lock.yaml
Remove whitespace in settings example file so users don't accidentally make the mistake of not deleting them 
Checklist: 
> chore: Remove whitespace in settings example file

- docs/docs/user_guide/sidebar/admin/auth/introduction.md
Update broken hyper link in document
> docs: documentation hyper link

- addons/addon-base-raas/packages/base-raas-services/lib/environment/__tests__/environment-mount-service.test.js
- addons/addon-base-raas/packages/base-raas-services/lib/environment/environment-mount-service.js
GALI-455 
Added delete capability for R/W.
Checklist: 
> fix: added delete permissions

- addons/addon-base-raas/packages/base-raas-services/lib/helpers/is-role.js
- addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
- addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js
GALI-587
Fix to protect against: A researcher can gain access to any study regardless of permissions.
Checklist: 
> fix: adding validation for enhanced study security

- addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
- addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js
N/A
Bug fix for ensuring R/W studies could be listed on studies page.
Checklist: 
> fix: readwrite studies should be listed

- CHANGELOG.md
- addons/addon-base-raas/packages/base-raas-services/lib/environment/environment-mount-service.js
- addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
- addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js
N/A
Fix an authz bug on update study API
Checklist: 
> fix: adding validation for study update route

- README.md
- docs/docs/user_guide/account_structure.md
- main/solution/prepare-master-acc/README.md
Issue #, if available: #225 
- Removing dead links
> fix: delete dead links

- .github/workflows/deploy-env.yml
* Add sudo for apt-get dependency install 
Checklist: 
> fix: apt-get permission issue

- CHANGELOG.md
* Updated the change log to reflect 1.4.3 release
> Updated change log for 1.4.3 release

- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/studies/Study.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/studies/StudyRow.js
- addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
- addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js
- main/solution/ui/src/models/hello/HelloStore.js
GALI-606
Upload Files button the studies page would not appear for users who are study admins AND possess R/W or R/O permission. This fix ensures study admins and R/W permitted users have access to the Upload Files button.
Checklist: 
> fix: Upload Files button disappears for R/W users

- addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/environment-resource-service.test.js
- addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/legacy/environment-resource-service.js
GALI-638
The change in implementation takes into consideration that updates to the bucket policy and KMS policy could have failed previously and therefore API calls to update them should succeed irrelevant of the resource usage state suggested by the DB.
Unit tests have been added to confirm the same.
Checklist: 
> Feat: Legacy env-resource-service tests

- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/data-sources/DataSourceAccountStore.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/data-sources/DataSourceAccountsStore.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/models/data-sources/DataSourceStackInfoStore.js
GALI-646
Shortened tickPeriod for UI stores for BYOB components.
Checklist: 
> fix: DS lists are set with a shorter tickPeriod

- addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
- addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js
- main/solution/backend/src/lambdas/open-data-scrape-handler/handler-impl.js
* Update brach name to 'main' for open data scrape
* Check existing study record category for study update
Checklist: 
> fix: open data scraper bugfix

- addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/data-sources/DataSourceAccountCard.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/data-sources/DataSourceStudyRow.js
- addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/data-sources/register/SubmitStep.js
- main/solution/backend/config/infra/functions.yml
- main/solution/backend/src/lambdas/data-source-reachability-daily/handler.js
- main/solution/backend/src/lambdas/data-source-reachability/__tests__/handler.test.js
- main/solution/backend/src/lambdas/data-source-reachability/handler.js
1. Once CfN is updated for an already available DS Account in order to add a new study, SWB should check reachability of all pending studies under this account. When the Data Source Study is registered, nothing is done currently to update its status until a user manually tests connection for the study. Current workaround is to hit “Test Connection“ on the new study.
2. When any step reports an error while registering a DS account/study the UI still permits the user to go forward with CfN stack update/create.
1. Adding reachability check to existing lambda for checking and updating status of unreachable DS studies.
2. Removing Next button and adding Cancel button when any DS registration step displays an error.
Checklist: 
By submitting this …
> Feat byob fixes

- .github/PULL_REQUEST_TEMPLATE.md
- openapi.yaml
Add OpenAPI file for the following endpoints:
BYOB:
API | Path | Action
-- | -- | --
List | /api/data-sources/accounts | GET
AttemptReach | /api/data-sources/accounts/ops/reachability | POST
RegisterAccount | /api/data-sources/accounts | POST
Update | /api/data-sources/accounts/:id | PUT
RegisterBucket | /api/data-sources/accounts/:id/buckets | POST
RegisterStudy | /api/data-sources/accounts/:id/buckets/:name/studies | POST
CreateAccountCfn | /api/data-sources/accounts/:id/cfn | POST
ListStudiesForAccount | /api/data-sources/accounts/:id/studies | GET
Studies:
listStudy | /api/studies | GET
-- | -- | --
getStudy | /api/studies/:id | GET
getStudyPermissions | /api/studies/:id/permissions | GET
updateStudy | /api/studies/:id | PUT
createStudy | …
> docs: Add openAPI definition

- CHANGELOG.md
> docs: Change-log for 1.4.4

- addons/addon-base-rest-api/packages/base-controllers/lib/authentication-provider-controller.js
* Remove unused authZ provider logic
* Deployed and tested login, add user logic were not affected
Checklist: 
> refactor: Remove unused authZ provider logic

- openapi.yaml
Issue #, if available: GALI-654
Added APIs from following controller
1. [aws-accounts-controller.js](https://github.com/awslabs/service-workbench-on-aws/blob/master/addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/accounts-controller.js)
2. [compute-controller.js](https://github.com/awslabs/service-workbench-on-aws/blob/master/addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/compute-controller.js)
3. [costs-controller.js](https://github.com/awslabs/service-workbench-on-aws/blob/master/addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/costs-controller.js)
4. [indexes-controller.js](https://github.com/awslabs/service-workbench-on-aws/blob/master/addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/inde …
> docs: Add openAPI definition for User, Account, Index, Project, Compute and CfnTemplate management

- addons/addon-base-rest-api/packages/api-handler-factory/lib/handler.js
Add a log entry for ALL incoming requests. This complements the APIGW access logs since the requests parameters(query and body) are not logged in there. 
A couple of example log entries:
```json
{
"solutionName": "sw",
"envType": "prod",
"envName": "nesdev",
"logLevel": "info",
"logEventType": "incomingRequest",
"uid": "u-PvFZgnw5fl5nwqIia4F0P",
"authenticationProviderId": "internal",
"method": "GET",
"url": "/api/costs?groupByService=false&groupByUser=true&numberOfDaysInPast=30&scEnv=59d5a738-03bc-4b27-81ab-399c24f6c478",
"query": {
"groupByService": "false",
"groupByUser": "true",
"numberOfDaysInPast": "30",
"scEnv": "59d5a738-03bc-4b27-81ab-399c24f6c478"
},
"body": {}
}
```
```json
{
"solutionName": "sw",
"envType": "prod",
"envName": "nesdev",
"logLevel": …
```
> feat: log all incoming requests

- openapi.yaml
Issue #, if available: GALI-654
Follow up of the last PR: https://github.com/awslabs/service-workbench-on-aws/pull/268 to correct input params of UpdateUserRequest
Checklist: 
> docs: Update UpdateUser API with correct parameters

- openapi.yaml
* Add OpenAPI docs for authZ and user APIs
> docs: Add user and authN APIs in api docs

- openapi.yaml
chore: Added Open Api Docs for step-template-controller, workflow-controller, workflow-template-controller, and key-pair-controller
Validated API using https://editor.swagger.io/
Also test that import into POSTMAN worked correctly.
> docs: Added Open Api Docs for step-template-controller, workflow-controller, workflow-template-controller, and key-pair-controller

- addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/compute-controller.js
- addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/environment-controller.js
- main/config/settings/.defaults.yml
- openapi.yaml
1. Merging commit feat: Remove APIs for built-in workspaces and clarify documentation on the enableBuiltInWorkspaces flag (PR: 281)
2. Also merging the following commit: docs: Update UpdateUser API with correct parameters from PR: 272 which somehow disappeared after PR 280 was merged
3. Corrected UpdateCurrentUserInfo schema
Checklist: 
> feat: Remove APIs for built-in workspaces and clarify documentation on the enableBuiltInWorkspaces

- CHANGELOG.md
Update the version and date for latest release, and also updated the latest change log with remaining commits
Checklist: 
> docs: update change log for edit CIDR change

- .github/workflows/labeler.yml
* Fix syntax in labeler
* Tested locally with act 
> fix: labeler .yml syntax

- main/solution/infrastructure/config/infra/cloudformation.yml
Checklist: 
* Add description for CF template
> chore: Add description for CF template

- main/integration-tests/__test__/api-tests/studies/get-study.test.js
- main/integration-tests/__test__/api-tests/studies/update-study.test.js
- pnpm-lock.yaml
N/A
Error code fixed for study integ test per master branch
Checklist: 
> Fix: error code for study integ test

- main/integration-tests/support/resources/base/resource.js
- pnpm-lock.yaml
Add 'create' method to the Resource class
Checklist: 
> feat: add create to the resource class
