awslabs/service-workbench-on-aws

.github/PULL_REQUEST_TEMPLATE.md

Add a check list item for adding end-to-end tests if user is running manual tests

Add a check list item for adding end-to-end tests 

---

addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml
addons/addon-base-raas/packages/base-raas-post-deployment/lib/steps/create-service-catalog-portfolio.js
addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-connection-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js
addons/addon-base-raas/packages/base-raas-services/package.json
docs/docs/user_guide/sidebar/common/workspaces/introduction.md
main/solution/machine-images/config/infra/files/rstudio/set-password
pnpm-lock.yaml

GALI-450
1. Added the RStudio product template to the default SC portfolio (reused the built-in template and added SC-related output variables)
2. Reuse getRStudioUrl mechanism from the built-in environmentUrlService class, and integrated it into environmentScConnectionService. This provides the 'Connect' button in the UI that opens the RStudio authorized URL tab.
Checklist: 

RStudio for SC

---

addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/study-controller.js
addons/addon-base-raas/packages/base-raas-services/lib/schema/create-study.json
addons/addon-base-raas/packages/base-raas-services/lib/schema/update-study-permissions.json
addons/addon-base-raas/packages/base-raas-services/lib/schema/update-study.json
addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-permission-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/study/__tests__/study-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/study/study-permission-service.js
addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js

* Deny permissions change for Open Data study
* Enum for accessType changed to lower case to match existing permission case
* Added check to disallow ReadWrite accessType on Open Data Studies
* Added writeonly and readwrite permission levels for studies
* Disallow same user to have multiple non-admin permissions
* Allow UPLOAD access for users with write access
* Added new unit tests to verify check permissions functionality
Checklist: 
[✓] Have you successfully deployed to an AWS account with your changes? 
[✓] Have you linted your code locally prior to submission?
[✓] Have you written new tests for your core changes, as applicable?
[✓] Have you successfully ran unit tests and manual tests with your changes locally?
[] If you had to run …

Write permissions studies

---

addons/addon-base-raas/packages/base-raas-services/lib/plugins/env-provisioning-plugin.js

Not all workspace types have metaconnection output
Divided metaconnection outputValue retrieval for creating/deleting CNAME DNS record for RStudio.
Checklist: 

Bugfix: metaconnection check for rstudio

---

addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/external/sagemaker.cfn.yml
addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml
addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml
addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/__tests__/environment-sc-connection-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js
addons/addon-base-raas/packages/base-raas-services/lib/plugins/env-provisioning-plugin.js
main/solution/machine-images/config/infra/files/rstudio/set-password
main/solution/machine-images/config/infra/provisioners/provision-rstudio.sh

GALI-476
GALI-477
Added auto-stop scripts for Sagemaker and RStudio
Added security enhancement for RStudio (environments do not need to be open to internet anymore)
Checklist: 

feat: autostop SM and rstudio

---

addons/addon-base-raas-ui/packages/base-raas-ui/src/models/environments-sc/ScEnvironmentsStore.js
addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-rstudio-instance.cfn.yml
addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-service.js
addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/plugins/workflow-steps-plugin.js
addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/__test__/start-rstudio-environment-sc.test.js
addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/start-rstudio-environment/start-rstudio-environment-sc.js
addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/start-rstudio-environment/start-rstudio-environment-sc.yml
addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/stop-rstudio-environment/stop-rstudio-environment-sc.yml
addons/addon-environment-sc-api/packages/environment-sc-workflows/lib/plugins/workflows-plugin.js
addons/addon-environment-sc-api/packages/environment-sc-workflows/lib/workflows/start-rstudio-environment-sc.yml
addons/addon-environment-sc-api/packages/environment-sc-workflows/lib/workflows/stop-rstudio-environment-sc.yml
docs/docs/user_guide/sidebar/common/workspaces/accessing_a_workspace.md
main/solution/machine-images/README.md
main/solution/machine-images/config/infra/files/rstudio/set-password
main/solution/post-deployment/config/environment-files/bin/mount_s3.sh
main/solution/post-deployment/config/environment-files/bootstrap.sh

GALI-479
1. RStudio manual start/stop feature, managing CNAME updates and tested public key refresh
2. Added unit tests for RStudio start/stop
3. Tested Start/Stop functionality works as expected as long as DB status field is in sync
4. Bug fix: Study mounting on RStudio
Checklist: 

RStudio manual start-stop & BugFixes

---

addons/addon-base-raas/packages/base-raas-services/lib/account/__tests__/account-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/account/account-service.js
addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/provision-account/provision-account.js
main/solution/backend/config/infra/cloudformation.yml

* The change makes sts-caller-identity call in provision-account API to figure out accountId of the main account
* The main accountId is further used to whitelist in cross account role of member account so that main account can always assume root account roles
* I further tested the ec2 poll handler functionality and verified that poll handler lambda was able to successfully update the DynamoDB state which correctly reflected in the UI later.
Checklist: 

bugfix: Ensure that new cross account roles in member accounts can be assumed by main account

---

main/end-to-end-tests/cypress/integration/workspaces.spec.js

There's an error in the end to end tests when is is testing creating new workspaces. During creation of new workspace, it fails to select the correct project because the test is looking at the wrong CSS element class. Screenshot below. All elements in the drop down menu will have the class `item`, but not all elements will have the class `selected`
Checklist: 

fix (End to End test): Creating workspace with correct project

---

addons/addon-base-raas/packages/base-raas-post-deployment/lib/steps/__tests__/create-service-catalog-portfolio.test.js
addons/addon-base-raas/packages/base-raas-post-deployment/lib/steps/create-service-catalog-portfolio.js

GALI-481
Currently when an existing SC product template is updated and deployed to SWB, the auto-create code does not assign a name to the new provisioning artifact. This displays the new product version on SWB UI as "<ProductName> undefined".
To avoid this, the PR achieves the following:
1. Change the default "autoCreateVersion" variable to something simpler like "v1"
2. Add "Name" field in the params used in createProductArtifact().
3. Before attempting to create a new product artifact, call servicecatalog.ListProvisioningArtifacts() to retrieve latest version of product already in SC.
4. Assign the next logical version name to the "Name" field
Checklist: 
By submitting this pull request, I confirm that my contribution is made under the …

Apply version name to products out of the box

---

addons/addon-base-post-deployment/packages/base-post-deployment/lib/steps/add-auth-providers.js
addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/__tests__/provisioner-service.test.js
addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js
addons/addon-base-rest-api/packages/services/package.json
main/solution/post-deployment/config/infra/functions.yml
main/solution/post-deployment/config/settings/.defaults.yml
pnpm-lock.yaml

* Add new settings key cognitoUserPoolDomainPrefix with default value envName-solutionName
* Allow customized cognitoUserPoolDomainPrefix
* Pad random string if domain is not available 
* Retry another random string if padded domain is not available, till an availability is found
* Unit test - WIP 
Checklist: 

fix: domain name clashing issue

---

scripts/environment-delete.sh

The script `scripts/environment-delete.sh` can take incredible time to end. It is mostly due to the operations of cleaning the S3 buckets before trying to delete them (in order to avoid cloudformation errors). Last time it took 1 hour to run completely (because the version of SWB was up for several months and accumulated a lot of logs in its buckets). Several times I thought there might be an error with the script freezing my terminal whereas the script actually worked fine, but the operations take time and no progress was displayed. Also during this scenario I interrupted the script after it removed the backend stack. From then on it would crash at the beginning when trying to remove non-existing stacks.
The following commits aim at making things clear :
- commit …

chore: Env delete logs

---

addons/addon-base-raas/packages/base-raas-cfn-templates/src/plugins/cfn-templates-plugin.js
addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/storage-gateway/network-infrastructure.cfn.yml
addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/services-plugin.js
addons/addon-base-raas/packages/base-raas-services/lib/schema/storage-gateway-db-record.json
addons/addon-base-raas/packages/base-raas-services/lib/storage-gateway/__tests__/storage-gateway.test.js
addons/addon-base-raas/packages/base-raas-services/lib/storage-gateway/storage-gateway.js
addons/addon-base-raas/packages/base-raas-services/package.json
addons/addon-base-raas/packages/base-raas-workflow-steps/lib/plugins/workflow-steps-plugin.js
addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/__test__/create-network-infrastructure.test.js
addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/storage-gateway/create-network-infrastructure.js
addons/addon-base-raas/packages/base-raas-workflow-steps/lib/steps/storage-gateway/create-network-infrastructure.yml
addons/addon-base-raas/packages/base-raas-workflow-steps/package.json
addons/addon-base-raas/packages/base-raas-workflows/lib/plugins/workflows-plugin.js
addons/addon-base-raas/packages/base-raas-workflows/lib/workflows/create-network-infra.yml
main/solution/backend/config/infra/cloudformation.yml
main/solution/backend/config/settings/.defaults.yml
pnpm-lock.yaml

Issue #, if available: GALI-436
Added a workflow which does the following:
1. Provision EC2 instance, VPC, Subnet, Volume and Elastic IP using CloudFormation
2. Activate Storage Gateway
3. Add Volume to Storage Gateway
4. Persist the results to DynamoDB
Checklist: 

feat: add functionality for creating a Storage Gateway

---

main/solution/machine-images/config/infra/provisioners/provision-rstudio.sh

**Description of changes:**
RStudio users have no right to install new packages through the terminal.
I added git among the pre-installations of RStudio workspaces so one can bring his/her analysis from a git repository to the workspace. 
Researchers need to pull the code of there analysis in there RStudio workspaces because on many cases they do not start implementation from scratch in Service Workbench.
**Checklist:**

feat: add git preinstallation on Rstudio workspaces

---

addons/addon-base-ui/packages/base-ui/src/helpers/api.js

Query string parameters were getting duplicated in the url upon retries. This was causing intermittent failures on the Workspace Types page.
- Delete merged.params after they are added to the url to stop them from getting duplicated upon recursive retry calls
- This fixes an issue where the `Workspace Types` screen intermittently shows `Invalid version specified for filter. Valid values for version are *,latest` error under `AWS Service Catalog Products` section. That error happens when the initial call times out (because fetching Service Catalog Products is relatively slow operation) and the call is retried. 
Checklist: 

fix: Query string parameters were getting duplicated in the url

---

docs/docs/deployment/pre_deployment/prerequisites.md

**Issue** : Cost breakdowns were always empty in a version of SWB deployed in a test account.
**Description of changes:**
Cost allocation tags need to be activated in order to get actual cost reports.
We figured that this information was not included in the documentation yet. 
Feel free to correct it if you think of more exact formulations.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

docs:  add specific info to enable cost breakdowns

---

addons/addon-base-raas/packages/base-raas-services/lib/environment/__tests__/environment-mount-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/environment/environment-mount-service.js

GALI-455 (Partial)
These changes ensure that users who are admins of a particular study possess at least R/O access once they provision a workspace with that study mounted on it.
Checklist: 

Study Admin permission handling

---

addons/addon-base-raas/packages/base-raas-services/lib/environment/__tests__/environment-mount-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/environment/environment-mount-service.js
addons/addon-base-raas/packages/base-raas-services/lib/study/study-service.js

GALI-455 (partial)
Adding fixes affecting the UI for handling R/W permission level access.
Adding required permissions for multipart upload and putObjectAcl for study bucket policy.
Checklist: 

fix: UI fixes and permissions for bucket policy

---

addons/addon-base-raas/packages/base-raas-services/lib/environment/environment-mount-service.js
addons/addon-base/packages/services/lib/iam/iam-service.js

N/A
Added logic to handle EC2 Windows permission propagation scenarios, with known S3 permission policy names.
Checklist: 

fix: handling policy names for windows envs

---

main/solution/post-deployment/config/environment-files/bin/mount_s3.sh

N/A
Removing dependency on region while mounting S3 studies on workspaces. This allows studies in a different region to be mounted on workspaces.
Checklist: 

fix: removing region from mount_s3 script

---

main/solution/machine-images/config/infra/files/rstudio/nginx.conf

**Object of this PR**
This PR aims to fix an error in the default RStudio workspaces. This error prevents users to upload data from their computer to the RStudio server.
**Description of the error :**
When a user clicks on the "upload" button available on the RStudio interface, the following error is raised.  
The "upload" pop-up frizzes the whole page, and no upload is performed.  
It concerns too-restrictive CSP headers that prevent uploads from any domain name.  
**Description of changes:**
I modified the CSP headers and the X-Frame-Options headers of the nginx server to allow uploads from the same own domain name (via the HTTPS RStudio interface).
I tried those changes. It erases the error, and allows to upload data as expected without errors.
**Checklist:** 
By submitting this pull …

fix: changed RStudio CSP headers to allow uploads from same-origin

---

addons/addon-base-raas/packages/base-raas-rest-api/lib/plugins/services-plugin.js
addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/roles-only/__tests__/filesystem-role-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/roles-only/application-role-service.js
addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/roles-only/filesystem-role-service.js
addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/roles-only/helpers/entities/application-role-methods.js
addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/roles-only/helpers/entities/filesystem-role-methods.js

This PR wraps up the work related to the implementation of the role allocation core logic.  This PR includes the file system service implementation.  Together with the application role service (submitted in a previous PR), these two services are the core pieces for the role allocation logic.  The file system service code is heavily documented to aid with understanding this nontrivial allocation logic.  The following is a primer and a high level logic of how the file system service role works.
**Primer**
- We capture the relations between four items: fs role, study, member account and environment.
- We keep the relationship information in three database items across two tables.
1. Study to fs roles, this is a one-to-many relationship (but we need to make it many-to-many in the future if we …

feat: bring your own bucket - role allocation implementation

---

main/solution/machine-images/config/infra/provisioners/provision-rstudio.sh

**Motivation**
We're currently trying to reproduce a biomedical analyses using RStudio workspaces.
We faced the following blockers when trying to install R libraries :
- the workspace misses system packages required by R to install packages (like 'devtools' or 'tidyverse')
- multiple broadly used R libraries require R>=3.5, whereas only R3.4 was installed through amazon-linux-extras repositories.
For security considerations, users do not have root access to the workspaces, so system packages have to be preinstalled in the AMI of the workspace.
**Description of changes:**
The changes here consist of modifying the provisioning script used to build RStudio AMIs : `main\solution\machine-images\config\infra\provisioners\provision-rstudio.sh`.
The following modifications make them meet the …

feat: install R3.6 and system packages required for research

---

addons/addon-base-raas/packages/base-raas-services/lib/data-source/__tests__/environment-resource-service.test.js
addons/addon-base-raas/packages/base-raas-services/lib/data-source/access-strategy/legacy/environment-resource-service.js

Issue #, if available: GALI-615
* Added the legacy methods for adding and removing S3 bucket and KMS policies
* Tested by bringing two workspaces and terminating them. Verified that workspaces could access the study appropriately and bucket and KMS policies were correctly reflected later when the workspaces were terminated.
Checklist: 
* [] If you had to run manual tests, have you considered automating those tests by adding them to [end-to-end tests](../main/end-to-end-tests/README.md)?

feat: Added code for add/remove permissions for internal studies which use bucket policy

---

addons/addon-raas-s3-copy/packages/s3-synchronizer/src/s3-download.go
addons/addon-raas-s3-copy/packages/s3-synchronizer/src/s3-synchronizer.go

Issue #, if available: GALI-645
If workspace and S3 bucket were in different regions, we would see the files being listed in windows but it won't have any contents. After reading of the code, it seems like we were using the correct region centric AWS session only for file listing and not for file copying, writing or deleting. In this change I have moved the logic of finding the correct region upstream and based on that create the correct S3 session.
I didn't find a good way to unit test this change, so I will be extending our old backlog item to improve the unit testing or better add this as part of integ testing.
Checklist: 

Fixed cross-region S3 bucket access for windows

---

addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/internal/api-key-service.js
main/solution/backend/config/infra/cloudformation.yml

* Add two ApiKeys table back
* Update validateKey method to throw error on all calls 
* Deployed to environments with or without the previous patch, both deployed successfully  
* Validated both environments for log in, log out, create new user
* Validated using key in the ApiKeys table throw Unauthorized error
* Validated triggering /api-keys throw Not Found error
Checklist: 

fix: Add tables back for postmortem analysis

---

main/solution/backend/serverless.yml

Enable ApiGW access logs. The values that are logged were handpicked from the [ApiGW List of Log Variables](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference%3Fcmpid=docs_apigateway_console)
example log entry:
```json
{
"authorizer.principalId": "u-PvFZgnw5fl5nwqIia4F0P",
"error.message": "-",
"extendedRequestId": "ZuT4rGDNoAMFxXw=",
"httpMethod": "GET",
"identity.sourceIp": "72.21.196.66",
"integration.error": "-",
"integration.integrationStatus": "200",
"integration.latency": "79",
"integration.requestId": "67394741-90ae-4c6c-94fb-df8bf7be33ec",
"integration.status": "200",
"path": "/nesdev/api/user-roles",
"requestId": "468a1b4d-3015-4901-b749-37e4e0551029",
"responseLatency": …
```

feat: enable API Gateway access logs

---

addons/addon-base/packages/services/lib/logger/__tests__/log-transformer.test.js
addons/addon-base/packages/services/lib/logger/log-transformer.js
main/packages/services/lib/plugins/services-plugin.js
main/solution/post-deployment/src/lambdas/post-deployment/plugins/services-plugin.js

Some addons were passing an object instead of an array as `fieldsToMask` and that inadvertently lead to the logger not masking anything. This fixes it
Also changed LogTransformer to crash for invalid `fieldsToMask` to prevent this issue in the future.
Checklist: 
* [n/a] If you had to run manual tests, have you considered automating those tests by adding them to [end-to-end tests](../main/end-to-end-tests/README.md)?

fix: use correct fieldsToMask in the logger

---

addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/compute-controller.js
addons/addon-base-raas/packages/base-raas-rest-api/lib/controllers/environment-controller.js
main/config/settings/.defaults.yml

Issue #, if available:  GALI-684
Disabling built-in related APIs since the feature isn't being used by any known customers. I have updated the documentation on the flag to reflect that. We will bring the feature back based on customer interest and re-evaluating it on our side.
I tested by calling the APIs from postman and get an expected Error. Did this by deploying the code locally and via APIGateway endpoint both.
Paths I tested: {{baseUrl}}/api/compute/platforms/ and {{baseUrl}}/api/workspaces/built-in
Checklist: 

feat: Remove APIs for built-in workspaces and clarify documentation on the enableBuiltInWorkspaces flag

---

.github/workflows/labeler.yml

Add GH workflow to tag size on PR
Workflow tested in another repository, see clip below for details: 

chore: add PR size labeler

---

addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/users/UserOnboarding.js

Issue #, if available: GALI-20
* Note that the change is only applicable for external-researchers, so in order to test the change I had to enable built-in and external-researcher config
* Verified that I was able to create/connect/terminate SageMaker instance
* Verified that I was able to create/terminate EMR
* RStudio/Windows/Linux EC2 are not supported for external-researchers, and they don't show up as an option for provisioning
Out of scope but broken
* Stopping SageMaker and connecting with EMR is broken currently, and I will create a separate issue about this
* Also note that we have permissions to createRole with permissions boundary. That is also overly permissive but the change would be more involved. I will create a separate issue in our backlog for this …

fix: Made external researcher used UserOnboarding template less permissive

---

addons/addon-base-raas/packages/base-raas-services/lib/schema/update-user.json
addons/addon-base-raas/packages/base-raas-services/lib/user/__tests__/user-service.test.js
addons/addon-base/packages/services/lib/schema/update-user.json
addons/addon-base/packages/services/lib/user/__tests__/user-service.test.js

This change fixes authentication of users who are added by admin from ServiceWorkbench UI directly
With userId PR https://github.com/awslabs/service-workbench-on-aws/pull/148 we had broken the above use case since the field `usernameInIdp` was removed from update schema. With users added by admin, this property is tried to be added back to user table[1][2] during authentication but the update fails since the field was removed from schema. Note that when user does self registration via idp the field `usernameInIdp` is already present from idp authentication and since create-user schema supports it, the field is added successfully. I figured that keeping the field around is useful so added it to update schema as well. It seems like removing the …

fix: Added usernameInIdp property to update user schema

---

scripts/run-integration-tests.sh

N/A
Integration test script to create empty XML result file when test config not found.
Checklist: 

fix: Creating empty XML file for no test config
